language: swift
matrix:
  include:
    - os: linux
      dist: xenial
      language: generic
      env: SWIFT_VERSION=5.0.2
      script:
        - export PATH=`sh Tests/install-swift-on-linux.sh`:$PATH
        - swift build -c release
        - swift test -c release -Xswiftc -enable-testing

    - os: linux
      dist: bionic
      language: generic
      env: SWIFT_VERSION=5.0.2
      script:
        - export PATH=`sh Tests/install-swift-on-linux.sh`:$PATH
        - swift build -c release
        - swift test -c release -Xswiftc -enable-testing

    - os: osx
      osx_image: xcode10.3
      script:
        - xcodebuild -project Cloche.xcodeproj -scheme 'Cloche macOS' -configuration Release ENABLE_TESTABILITY=YES build test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J Cloche

    - os: osx
      osx_image: xcode10.3
      script:
        - xcodebuild -project Cloche.xcodeproj -scheme 'Cloche iOS' -configuration Release ENABLE_TESTABILITY=YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.4' build test

    - os: osx
      osx_image: xcode10.3
      script:
        - xcodebuild -project Cloche.xcodeproj -scheme 'Cloche tvOS' -configuration Release ENABLE_TESTABILITY=YES -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 4K,OS=12.4' build test

    - os: osx
      osx_image: xcode10.3
      script:
        - xcodebuild -project Cloche.xcodeproj -scheme 'Cloche watchOS' -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm,OS=5.3' build
